DROP TABLE DEPT;
DROP TABLE EMP;
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;

CREATE TABLE DEPT (
DEPT_ID NUMBER(10)NOT NULL,
DEPT_NAME VARCHAR2(25) NOT NULL,
CONSTRAINT DEP_PK PRIMARY KEY(DEPT_ID)
);
/
CREATE TABLE EMP (
EMP_ID NUMBER(10)NOT NULL,
EMP_FIRSTNAME VARCHAR2(25) NOT NULL,
EMP_LASTNAME VARCHAR2(25) NOT NULL,
DEPT_ID NUMBER(10)NOT NULL,
SALARY NUMBER(10),
EMP_EMAIL VARCHAR2(25) NOT NULL,
CONSTRAINT EMP_PK PRIMARY KEY(EMP_ID),
CONSTRAINT DEP_FK FOREIGN KEY(DEPT_ID) REFERENCES DEPT(DEPT_ID)
);
/
INSERT INTO DEPT(DEPT_ID, DEPT_NAME) VALUES
(1, 'ACCOUNTING');
INSERT INTO DEPT(DEPT_ID, DEPT_NAME) VALUES
(2, 'SALES');
INSERT INTO DEPT(DEPT_ID, DEPT_NAME) VALUES
(3, 'IMAGINEERING');
/
INSERT INTO EMP(EMP_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPT_ID, SALARY, EMP_EMAIL) VALUES 
(1, 'JON', 'SMITH', 1, 20000, 'JSMITH@GMAIL.COM');
INSERT INTO EMP(EMP_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPT_ID, SALARY, EMP_EMAIL) VALUES 
(2, 'SAM', 'TARLEY', 1, 30000, 'STARLEY@GMAIL.COM');
INSERT INTO EMP(EMP_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPT_ID, SALARY, EMP_EMAIL) VALUES 
(3, 'LIZ', 'KREISCHER', 2, 40000, 'LKREISCHER@GMAIL.COM');
INSERT INTO EMP(EMP_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPT_ID, SALARY, EMP_EMAIL) VALUES 
(4, 'ALEX', 'JONES', 2, 50000, 'AJONES@GMAIL.COM');
INSERT INTO EMP(EMP_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPT_ID, SALARY, EMP_EMAIL) VALUES 
(5, 'ROB', 'DELANEY', 3, 60000, 'RDELANEY@GMAIL.COM');
INSERT INTO EMP(EMP_ID, EMP_FIRSTNAME, EMP_LASTNAME, DEPT_ID, SALARY, EMP_EMAIL) VALUES 
(6, 'TYLER', 'JOHNSON', 3, 70000, 'TJOHNSON@GMAIL.COM');
/
